---
title: "Modeling precipitation patterns in South America due to the impact of water availability on crop yields"
subtitle: "Final Project for ENV797: Time Series Analysis"
author: "Chloe Young, Gaby Czarniak, and Weilin Wang"
date: "April 25, 2025"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

# Introduction
This final project uses time series analysis to better understand changes in precipitation patterns in Argentina, Brazil, and Colombia, as we were interested in the continent of South America and these three countries are major agricultural producers of key crops globally. For context, Brazil and Argentina are two of the largest soybean producers in the world, with April 2025 estimates placing Brazil at producing 152 million tonnes—the largest soybean producer among Agricultural Market Information System (AMIS) countries—and Argentina producing 48.21 million tonnes—the third-largest soybean producing AMIS country—in 2023/2024, respectively (AMIS, 2025). For reference, the United States produced 113.27 million tonnes of soybean in 2023/2024 (AMIS, 2025). In terms of soybean exports, Brazil leads by far and Argentina comes in fourth among AMIS countries (AMIS, 2025). Colombia is a leading producer of coffee, bananas, flowers, rice, maize, palm oil, and more (Santana, n.d.). Brazil is also a leading producer of coffee, sugarcane, and corn, among other crops (IFAD, n.d. a.). In addition to soybeans, Argentina is a leading producer of wheat, corn, and wine, among other crops (ITA, 2022).

# Motivation
Since in 2023 agriculture represented 7% of GDP in Argentina, 6.2%  in Brazil, and 8.7% in Colombia, this group was interested in factors that could have a major impact on crop yield, one of which is precipitation (IFAD, n.d. b.). Not only is global supply of a crop like soybean partially dependent on crop yields in Brazil and Argentina, for example, but within Argentina, Brazil, and Colombia, crop production impacts the labor force, too. In Colombia, for instance, agriculture accounts for 16% of employment (IFAD, n.d. b.). In terms of the motivation behind looking into precipitation data, specifically, over 39 million hectares of land in Argentina are cultivated for farming and ranching, while only 5% of these lands have irrigation systems (ITA, 2022). As water availability is key to food production (FAO, 2015), precipitation variability can very crucially impact agricultural planning. 

# Relevance
Questions around changing precipitation patterns are particularly relevant given changing frequency and intensity of precipitation due to global warming (Myhre et al., 2019). The IPCC warns that rarer extreme precipitation events will become more frequent with more global warming (Seneviratne et al., 2021). The Food and Agriculture Organization has highlighted the importance of understanding “spatial changes in precipitation, in intensity and seasonal distribution” (FAO, 2015). Precipitation variability differs significantly by region. Understanding regional differences can help develop targeted adaptation strategies for, it is hoped, a more secure food system.

# Objectives
Given data availability and the scope of this project, we evaluate the performance of different models used for time series analysis in fitting precipitation data for Brazil, Argentina, and Colombia, at the country level. The objectives are to determine:
Using a training set of historical values and testing against more recent values, which model best fits and forecasts precipitation data for Brazil, Argentina, and Colombia?
Is the magnitude of seasonality changing over time?
The latter question is a question of interest in relation to the IPCC findings that extreme precipitation events will be increasing in frequency and intensity, with complex spatial distributions (Seneviratne, 2021).

# Dataset information
The dataset utilized was produced by the University of East Anglia’s Climate Research Unit (University of East Anglia - Climatic Research Unit, 2025). The first iteration of this data was published in 2000, and it has been continuously updated and upgraded since. The most recent version was updated just recently on March 19th of 2025, and it includes a high resolution, monthly 0.5 degree latitude by 0.5 degree longitude grid of land based observations from 1901 to 2024. They look at 10 different variables: Mean 2m temperature, diurnal 2m temperature range, precipitation rate, vapor pressure, wet days, cloud cover, frost days, minimum 2m temperature, maximum 2m temperature, and potential evapo-transpiration. Due to the relationship between crop yields and precipitation, and the importance of the agricultural sector in Brazil, Argentina, and Colombia, this report focused on the precipitation variable. The precipitation data was separated and imported to R studio in an Excel file: this initial data included monthly precipitation, seasonal values (MAM - spring, JJA -summer, SON - autumn, DJF - winter), and annual precipitation. 


# Methods
Data Processing & Time Series Creation
An initial search of the data was conducted to identify any missing values. Only the “DJF” column had one missing value—an NA. This NA was filled using the DJF column means for the sake of continuity, but the DJF column ended up not being utilized in the processes. Instead, monthly precipitation values were utilized, since this provided the most accurate depiction of seasonal patterns and additional trends. To format the data, the monthly precipitation columns and their dates were selected, and pivot_longer() was used to reshape the data so that there was a Date column including both month and year, which allowed for a chronological precipitation column. This reshaped dataset was exported as countrymonthly_data_long.csv. Using this cleaned data, a univariable monthly time series object beginning in January 1901 with a frequency of 12 was created.

**Add a table that summarizes your data structure (variables, units, ranges and/or central tendencies, data source if multiple are used, etc.). This table should inserted as a `kable` function in an R chunk. Just show the first 10 rows of your data. Do not include the code used to generate your table.**

Exploratory Analysis 
To visualize the data, a plot of the time series object was created, and this was followed by an exploration of its patterns and autocorrelation using ACF and PACF. This information was helpful in deciding which models to use, as it provided information on the seasonality and auto regression. The time series was also  decomposed using both additive and multiplicative models in order to separate trend, seasonal, and residual components, allowing for more clear visualization prior to creating models. Following this, a linear trend model was fit to the time series object.

Models
The data was split into training and testing data sets. The training data set covered January 1901 to December 2020, and the testing data set included January 2021 to December 2024. Then, five models were select to apply to the training data:

1. ARIMA
2. STL + ETS
3. ARIMA with Fourier Terms
4. TBATS
5. Neural Network Autoregression

Each model generated a forecast and their accuracies were assessed using the metrics ME, RMSE, MAE, MPE, MAPE, ACF1, and Theil’s U. Finally, an overlay plot with all forecasts plotted on one graph was generated, allowing for visual comparison between models.




# Models

## Brazil



## Argentina



## Colombia





# Summary and conclusion

## Major findings


## Conclusions to draw from these findings


## Limitations and insights on how to improve the model
Predicting changes in frequency and intensity of extreme precipitation events is deeply complex and, as stated in the IPCC Sixth Assessment report, “increases in the intensity of extreme precipitation at regional scales will vary, depending on the amount of regional warming, changes in atmospheric circulation and storm dynamics (high confidence)” (Seneviratne et al., 2019).
Regarding limitations, it should be noted that, while we use precipitation data at the country level, precipitation patterns can vary drastically within each country, which contain multiple and varying ecosystems. Forecasting precipitation levels at the country scale does not account for precipitation patterns across different regions within a country. To make these models more helpful, time series models could be used could to analyze and forecast precipitation within key crop-producing provinces; in Argentina, for instance, this could be the provinces of Santa Fe, Córdoba, and Buenos Aires, where climate, water tables, and precipitation vastly differ from the southern tip of Argentina’s Misiones, Tierra del Fuego, and Jujuy provinces. 


# Contribution statement of this report
Introduction, motivation, relevance, objectives, and limitations within the conclusion – Gaby
Dataset and methods – Chloe
Summary and conclusion – Weilin
Code & analysis for Brazil – Weilin
Code & analysis for Argentina – Gaby
Code & analysis for Colombia – Chloe

# Github repository link
https://github.com/chloeyoung26/CzarniakWangYoung_ENV797_TSA_FinalProject-.git 

# References
Food and Agriculture Organization of the United Nations (FAO). (2015). Climate change and food security: risks and responses. https://openknowledge.fao.org/server/api/core/bitstreams/a4fd8ac5-4582-4a66-91b0-55abf642a400/content. Accessed 6 April 2025. \
\
International Fund for Agriculture and Development (IFAD). (n.d. a.). Brazil. https://www.ifad.org/en/w/countries/brazil. Accessed 6 April 2025. \
\
International Fund for Agriculture and Development (IFAD). (n.d. b.). Colombia. https://www.ifad.org/en/w/countries/colombia. Accessed 6 April 2025. \
\
Santana, Andrés. (n.d.) Colombia as an agricultural powerhouse: The unfulfilled promise. Dutch Ministry of Agriculture, Fisheries, Food Security and Nature. https://www.agroberichtenbuitenland.nl/landeninformatie/colombia/achtergrond/agro-logistics. Accessed 6 April 2025. \
\
Myhre, G., Alterskjær, K., Stjern, C.W. et al. Frequency of extreme precipitation increases extensively with event rareness under global warming. Sci Rep 9, 16063 (2019). https://doi.org/10.1038/s41598-019-52277-4.  \
\
Seneviratne, S.I., X. Zhang, M. Adnan, W. Badi, C. Dereczynski, A. Di Luca, S. Ghosh, I. Iskandar, J. Kossin, S. Lewis, F. Otto, I. Pinto, M. Satoh, S.M. Vicente-Serrano, M. Wehner, and B. Zhou. (2021). Weather and Climate Extreme Events in a Changing Climate. In Climate Change 2021: The Physical Science Basis. Contribution of Working Group I to the Sixth Assessment Report of the Intergovernmental Panel on Climate Change. [Masson-Delmotte, V., P. Zhai, A. Pirani, S.L. Connors, C. Péan, S. Berger, N. Caud, Y. Chen, L. Goldfarb, M.I. Gomis, M. Huang, K. Leitzell, E. Lonnoy, J.B.R. Matthews, T.K. Maycock, T. Waterfield, O. Yelekçi, R. Yu, and B. Zhou (eds.)]. Cambridge University Press, Cambridge, United Kingdom and New York, NY, USA, pp. 1513–1766, https://doi.org/10.1017/9781009157896.013. \
\
United States International Trade Administration (ITA). (2022, Oct. 26). Argentina: Agricultural Industry. ITA Market Intelligence. <https://www.trade.gov/market-intelligence/argentina-agricultural-industry#:~:text=One%20of%20Argentina%27s%20most%20important%20economic%20sectors,beef%2C%20wine%2C%20soy%2C%20wheat%2C%20and%20other%20cereals> . Accessed 6 April 2025. \
\
World Bank Group. (n.d.). Agriculture, forestry, and fishing, value added (% of GDP). https://data.worldbank.org/indicator/NV.AGR.TOTL.ZS?end=2023&most_recent_value_desc=true&start=2020. Accessed 23 April 2025.
